CREATE SCHEMA EETDATA;
SET SCHEMA EETDATA;
CREATE TABLE IF NOT EXISTS GEBRUIKER (
id INTEGER PRIMARY KEY,
naam VARCHAR,
wachtwoord  VARCHAR,
);
CREATE TABLE IF NOT EXISTS GERECHT (
id INTEGER PRIMARY KEY,
naam VARCHAR,
vis BOOLEAN,
vlees BOOLEAN,
aantal_personen INTEGER,
gebruiker_id INTEGER
);
CREATE TABLE IF NOT EXISTS INGREDIENT (
id INTEGER PRIMARY KEY,
naam VARCHAR,
hoeveelheid INTEGER,
eenheid VARCHAR,
gerecht_id INTEGER,
gebruiker_id INTEGER
);

CREATE SEQUENCE "EETDATA"."GEBRUIKER_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "EETDATA"."GERECHT_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "EETDATA"."INGREDIENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;