CREATE SCHEMA GEBRUIKER;
SET SCHEMA GEBRUIKER;
CREATE SCHEMA GERECHT;
SET SCHEMA GERECHT;
CREATE SCHEMA INGREDIENT;
SET SCHEMA INGREDIENT;
CREATE TABLE IF NOT EXISTS GEBRUIKER (
id INTEGER PRIMARY KEY,
naam VARCHAR,
wachtwoord  VARCHAR,
);
CREATE TABLE IF NOT EXISTS GERECHT (
id INTEGER PRIMARY KEY,
naam VARCHAR,
vis BOOLEAN,
vlees BOOLEAN,
aantal_personen INTEGER,
gebruiker_id INTEGER
);
CREATE TABLE IF NOT EXISTS INGREDIENT (
id INTEGER PRIMARY KEY,
naam VARCHAR,
hoeveelheid INTEGER,
eenheid VARCHAR,
gerecht_id INTEGER,
gebruiker_id INTEGER
);

CREATE SEQUENCE "GEBRUIKER"."GEBRUIKER_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "GERECHT"."GERECHT_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE "INGREDIENT"."INGREDIENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCACHE NOCYCLE;